# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'marvelSuperHeroes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for marvelSuperHeroes
  pod 'Alamofire' 

  target 'marvelSuperHeroesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'marvelSuperHeroesUITests' do
    # Pods for testing
  end

end
